using Fluxy.DataAccess;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration.Memory;

namespace Fluxy.API.Configuration
{
    /// <summary>
    /// Loads the compose <c>.env</c> file as a configuration source.
    /// </summary>
    public static class DotEnvConfigurationExtensions
    {
        /// <summary>
        /// Name of the secrets file generated by <c>scripts\init-secrets.ps1</c>.
        /// </summary>
        public const string DefaultFileName = ".env";

        /// <summary>
        /// Keys of the postgres secrets inside the <c>.env</c> file. They are the same variables
        /// <c>compose.yaml</c> interpolates, so the app and compose cannot drift apart.
        /// </summary>
        private const string HostKey = "POSTGRES_HOST";
        private const string PortKey = "POSTGRES_PORT";
        private const string DatabaseKey = "POSTGRES_DB";
        private const string UsernameKey = "POSTGRES_USER";
        private const string PasswordKey = "POSTGRES_PASSWORD";

        /// <summary>
        /// Keys of the redis secrets inside the <c>.env</c> file. They are the same variables
        /// <c>compose.yaml</c> interpolates, so the app and compose cannot drift apart.
        /// </summary>
        /// <remarks>
        /// Only <c>REDIS_ACL_HASH</c> reaches the container; the app authenticates with the
        /// clear text <c>REDIS_PASSWORD</c>, which stays on the host.
        /// </remarks>
        private const string RedisHostKey = "REDIS_HOST";
        private const string RedisPortKey = "REDIS_PORT";
        private const string RedisUsernameKey = "REDIS_USER";
        private const string RedisPasswordKey = "REDIS_PASSWORD";

        /// <summary>
        /// Host and port to assume when the <c>.env</c> file does not override them. The postgres port
        /// is published on the host, so <c>localhost</c> is what the app connects to. A containerized
        /// app would need the service name <c>postgres</c> and could add <c>POSTGRES_HOST</c> to
        /// <c>.env.example</c> for that.
        /// </summary>
        private const string DefaultHost = "localhost";
        private const string DefaultPort = "5432";

        /// <summary>
        /// The same defaults for redis, which publishes 6379 the same way postgres publishes 5432.
        /// </summary>
        private const string DefaultRedisPort = "6379";

        /// <summary>
        /// How far above the content root the <c>.env</c> file is looked for. The content root of
        /// Fluxy.API is the project folder, while the file sits next to compose.yaml, so one level up
        /// is the expected case; a few more levels keep it working when the app is started from
        /// another working directory.
        /// </summary>
        private const int MaxParentDirectoryDepth = 3;

        /// <summary>
        /// Adds the <c>.env</c> file to the configuration.
        /// </summary>
        /// <param name="builder">Configuration builder to add the source to.</param>
        /// <param name="fileName">File name to look for, <see cref="DefaultFileName"/> by default.</param>
        /// <param name="contentRootPath">
        /// Directory the upward search starts from, normally
        /// <c>builder.Environment.ContentRootPath</c>. <see cref="string.Empty"/> starts the search
        /// from the current working directory.
        /// </param>
        /// <returns>
        /// The resolved absolute path of the loaded file, or <see langword="null"/> when no such file
        /// was found - a missing file is not an error here, because the same values can also come from
        /// user-secrets or environment variables.
        /// </returns>
        /// <remarks>
        /// The file becomes the lowest priority source, so a connection string configured in
        /// appsettings.json, in user-secrets or in environment variables always wins over the derived
        /// one. Because the derivation happens while reading the file, <c>POSTGRES_*</c> keys supplied
        /// as real environment variables are not picked up - in that case configure
        /// <c>ConnectionStrings:Postgres</c> directly.
        /// </remarks>
        public static string? AddDotEnvFile(
            this IConfigurationBuilder builder,
            string fileName = DefaultFileName,
            string contentRootPath = "")
        {
            var path = FindFileUpwards(fileName, contentRootPath);
            if (path is null)
            {
                return null;
            }

            var values = Parse(File.ReadAllLines(path));
            AddDerivedPostgresConnectionString(values);
            AddDerivedRedisConnectionString(values);

            // Inserted at the front on purpose: the last provider that knows a key wins, so the
            // .env file has to come first to stay the lowest priority one. Everything configured in
            // appsettings.json, in user-secrets or in environment variables overrides it.
            builder.Sources.Insert(0, new MemoryConfigurationSource { InitialData = values });

            return path;
        }

        /// <summary>
        /// Walks up from <paramref name="startDirectory"/> looking for <paramref name="fileName"/>
        /// and returns the full path of the first match.
        /// </summary>
        private static string? FindFileUpwards(string fileName, string startDirectory)
        {
            var directory = string.IsNullOrWhiteSpace(startDirectory)
                ? Directory.GetCurrentDirectory()
                : Path.GetFullPath(startDirectory);

            for (var depth = 0; depth <= MaxParentDirectoryDepth; depth++)
            {
                var candidate = Path.Combine(directory, fileName);
                if (File.Exists(candidate))
                {
                    return candidate;
                }

                var parent = Directory.GetParent(directory);
                if (parent is null)
                {
                    break;
                }

                directory = parent.FullName;
            }

            return null;
        }

        /// <summary>
        /// Parses <c>KEY=VALUE</c> lines into a configuration dictionary. Empty lines and comments
        /// are skipped, the key is everything before the first <c>=</c>, and surrounding quotes of
        /// the value are removed so that quoted values are usable as-is.
        /// </summary>
        private static Dictionary<string, string?> Parse(IEnumerable<string> lines)
        {
            var values = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);

            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed.Length == 0 || trimmed.StartsWith('#'))
                {
                    continue;
                }

                var separator = trimmed.IndexOf('=');
                if (separator < 1)
                {
                    continue;
                }

                var key = trimmed[..separator].Trim();
                var value = trimmed[(separator + 1)..].Trim();

                if (key.Length == 0)
                {
                    continue;
                }

                if (value.Length >= 2
                    && ((value[0] == '"' && value[^1] == '"') || (value[0] == '\'' && value[^1] == '\'')))
                {
                    value = value[1..^1];
                }

                values[key] = value;
            }

            return values;
        }

        /// <summary>
        /// Composes <c>ConnectionStrings:Postgres</c> from the <c>POSTGRES_*</c> secrets of the
        /// <c>.env</c> file, so the credentials generated by <c>scripts\init-secrets.ps1</c> are used
        /// as they are, without keeping a second copy of the password.
        /// This is the only place in this file that knows about compose specific key names.
        /// </summary>
        /// <remarks>
        /// A partial set of secrets is ignored, so the data access layer fails with one descriptive
        /// error instead of connecting with an empty password.
        /// </remarks>
        private static void AddDerivedPostgresConnectionString(Dictionary<string, string?> values)
        {
            if (!values.TryGetValue(DatabaseKey, out var database) || string.IsNullOrWhiteSpace(database)
                || !values.TryGetValue(UsernameKey, out var username) || string.IsNullOrWhiteSpace(username)
                || !values.TryGetValue(PasswordKey, out var password) || string.IsNullOrWhiteSpace(password))
            {
                return;
            }

            var host = values.TryGetValue(HostKey, out var configuredHost) && !string.IsNullOrWhiteSpace(configuredHost)
                ? configuredHost
                : DefaultHost;
            var port = values.TryGetValue(PortKey, out var configuredPort) && !string.IsNullOrWhiteSpace(configuredPort)
                ? configuredPort
                : DefaultPort;

            values[$"ConnectionStrings:{ServiceCollectionExtensions.PostgresConnectionName}"] = string.Join(';',
                $"Host={host}",
                $"Port={port}",
                $"Database={database}",
                $"Username={username}",
                $"Password={password}");
        }

        /// <summary>
        /// Composes <c>ConnectionStrings:Redis</c> from the <c>REDIS_*</c> secrets of the
        /// <c>.env</c> file, in the format StackExchange.Redis parses: comma separated options
        /// rather than the semicolon separated pairs Npgsql uses.
        /// </summary>
        /// <remarks>
        /// The user name is not optional. The compose redis runs with <c>user default off</c>,
        /// so an unauthenticated connection is impossible and a string without
        /// <c>user=</c> would be rejected. <c>abortConnect=false</c> is requested because
        /// <c>AddRedis</c> forces it anyway, and having it visible in the file makes the
        /// start-up tolerance of a missing redis obvious to whoever reads it.
        /// </remarks>
        private static void AddDerivedRedisConnectionString(Dictionary<string, string?> values)
        {
            if (!values.TryGetValue(RedisUsernameKey, out var username) || string.IsNullOrWhiteSpace(username)
                || !values.TryGetValue(RedisPasswordKey, out var password) || string.IsNullOrWhiteSpace(password))
            {
                return;
            }

            var host = values.TryGetValue(RedisHostKey, out var configuredHost) && !string.IsNullOrWhiteSpace(configuredHost)
                ? configuredHost
                : DefaultHost;
            var port = values.TryGetValue(RedisPortKey, out var configuredPort) && !string.IsNullOrWhiteSpace(configuredPort)
                ? configuredPort
                : DefaultRedisPort;

            values[$"ConnectionStrings:{ServiceCollectionExtensions.RedisConnectionName}"] = string.Join(',',
                $"{host}:{port}",
                $"user={username}",
                $"password={password}",
                "abortConnect=false");
        }
    }
}
