using Fluxy.Application.Services.Email;
using Fluxy.Application.Services.Security;
using Fluxy.DataAccess;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration.Memory;

namespace Fluxy.API.Configuration
{
    /// <summary>
    /// Loads the <c>.env</c> file as a configuration source, and derives the application
    /// settings from it that no tracked file should hold.
    /// </summary>
    /// <remarks>
    /// The file serves two masters. Compose reads it directly for the passwords of postgres,
    /// pgadmin and redis, and this class reads the same values to compose the connection strings -
    /// so one generated file configures both halves without a second copy of any password. The
    /// reCAPTCHA secret and the SMTP credentials are consumed by the application alone; compose
    /// ignores variables it does not interpolate, so they simply sit unused there.
    /// </remarks>
    public static class DotEnvConfigurationExtensions
    {
        /// <summary>
        /// Name of the secrets file generated by <c>scripts\init-secrets.ps1</c>.
        /// </summary>
        public const string DefaultFileName = ".env";

        /// <summary>
        /// Keys of the postgres secrets inside the <c>.env</c> file. They are the same variables
        /// <c>compose.yaml</c> interpolates, so the app and compose cannot drift apart.
        /// </summary>
        private const string HostKey = "POSTGRES_HOST";
        private const string PortKey = "POSTGRES_PORT";
        private const string DatabaseKey = "POSTGRES_DB";
        private const string UsernameKey = "POSTGRES_USER";
        private const string PasswordKey = "POSTGRES_PASSWORD";

        /// <summary>
        /// Keys of the redis secrets inside the <c>.env</c> file. They are the same variables
        /// <c>compose.yaml</c> interpolates, so the app and compose cannot drift apart.
        /// </summary>
        /// <remarks>
        /// Only <c>REDIS_ACL_HASH</c> reaches the container; the app authenticates with the
        /// clear text <c>REDIS_PASSWORD</c>, which stays on the host.
        /// </remarks>
        private const string RedisHostKey = "REDIS_HOST";
        private const string RedisPortKey = "REDIS_PORT";
        private const string RedisUsernameKey = "REDIS_USER";
        private const string RedisPasswordKey = "REDIS_PASSWORD";

        /// <summary>
        /// Host and port to assume when the <c>.env</c> file does not override them. The postgres port
        /// is published on the host, so <c>localhost</c> is what the app connects to. A containerized
        /// app would need the service name <c>postgres</c> and could add <c>POSTGRES_HOST</c> to
        /// <c>.env.example</c> for that.
        /// </summary>
        private const string DefaultHost = "localhost";
        private const string DefaultPort = "5432";

        /// <summary>
        /// The same defaults for redis, which publishes 6379 the same way postgres publishes 5432.
        /// </summary>
        private const string DefaultRedisPort = "6379";

        /// <summary>Private key of the reCAPTCHA pair, shared with Google and with nothing else.</summary>
        private const string RecaptchaSecretKey = "RECAPTCHA_SECRET_KEY";

        /// <summary>
        /// Credentials and address of the SMTP server the installation mails through.
        /// </summary>
        /// <remarks>
        /// <c>SMTP_USER</c> and <c>SMTP_PASSWORD</c> are the only credentials here. The rest is
        /// ordinary configuration, kept in this file anyway so that setting up a mail server never
        /// means editing a tracked file.
        /// </remarks>
        private const string SmtpHostKey = "SMTP_HOST";
        private const string SmtpPortKey = "SMTP_PORT";
        private const string SmtpUsernameKey = "SMTP_USER";
        private const string SmtpPasswordKey = "SMTP_PASSWORD";
        private const string SmtpUseTlsKey = "SMTP_USE_TLS";
        private const string SmtpFromKey = "SMTP_FROM";

        /// <summary>
        /// Switch for the browser policy, and the comma separated list of origins it allows.
        /// </summary>
        /// <remarks>
        /// Neither is a secret, but both are per-machine, which is the reason they live in a
        /// gitignored file rather than in a tracked one: the origin that has to be allowed is the
        /// one this machine happens to serve the SPA from, and a committed list would be wrong on
        /// every machine that is not the author's.
        ///
        /// <c>CORS_ALLOWED_ORIGINS</c> cannot go through <see cref="ApplicationSecretKeys"/> because
        /// that maps one flat key to one flat key, and this is a list.
        /// </remarks>
        private const string CorsEnabledKey = "CORS_ENABLED";
        private const string CorsOriginsKey = "CORS_ALLOWED_ORIGINS";

        /// <summary>
        /// Every <c>.env</c> key that feeds an application setting, paired with the configuration key
        /// it feeds.
        /// </summary>
        /// <remarks>
        /// Compose interpolates only the variables it names in <c>compose.yaml</c> and ignores the
        /// rest, so the app's own secrets live in the same file as the infrastructure ones rather
        /// than in a second place with its own rules.
        ///
        /// The section names come from the options types themselves, so a section that is renamed
        /// cannot silently stop being fed.
        ///
        /// The order is not significant: nothing here is derived from anything else, unlike the two
        /// connection strings.
        /// </remarks>
        private static readonly (string EnvKey, string ConfigurationKey)[] ApplicationSecretKeys =
        [
            (RecaptchaSecretKey, $"{RecaptchaOptions.SectionName}:SecretKey"),
            (SmtpHostKey, $"{EmailOptions.SectionName}:Host"),
            (SmtpPortKey, $"{EmailOptions.SectionName}:Port"),
            (SmtpUsernameKey, $"{EmailOptions.SectionName}:User"),
            (SmtpPasswordKey, $"{EmailOptions.SectionName}:Password"),
            (SmtpUseTlsKey, $"{EmailOptions.SectionName}:UseTls"),
            (SmtpFromKey, $"{EmailOptions.SectionName}:From")
        ];

        /// <summary>
        /// How far above the content root the <c>.env</c> file is looked for. The content root of
        /// Fluxy.API is the project folder, while the file sits next to compose.yaml, so one level up
        /// is the expected case; a few more levels keep it working when the app is started from
        /// another working directory.
        /// </summary>
        private const int MaxParentDirectoryDepth = 3;

        /// <summary>
        /// Adds the <c>.env</c> file to the configuration.
        /// </summary>
        /// <param name="builder">Configuration builder to add the source to.</param>
        /// <param name="fileName">File name to look for, <see cref="DefaultFileName"/> by default.</param>
        /// <param name="contentRootPath">
        /// Directory the upward search starts from, normally
        /// <c>builder.Environment.ContentRootPath</c>. <see cref="string.Empty"/> starts the search
        /// from the current working directory.
        /// </param>
        /// <returns>
        /// The resolved absolute path of the loaded file, or <see langword="null"/> when no such file
        /// was found - a missing file is not an error here, because the same values can also come from
        /// user-secrets or environment variables.
        /// </returns>
        /// <remarks>
        /// The file becomes the lowest priority source, so anything configured in appsettings.json,
        /// in user-secrets or in environment variables always wins over what is derived here. Two
        /// consequences are worth remembering, because both have surprised someone already:
        ///
        /// <list type="bullet">
        /// <item>
        /// A key that exists in appsettings.json <em>shadows</em> the file even when the file has a
        /// real value for it. That is why no credential appears in appsettings.json at all: a
        /// placeholder such as <c>"SecretKey": ""</c> is not harmless, it silently wins over the
        /// secret someone put in <c>.env</c>.
        /// </item>
        /// <item>
        /// Because the derivation happens while reading the file, <c>POSTGRES_*</c> or
        /// <c>SMTP_*</c> keys supplied as real environment variables are not picked up. In that
        /// setup configure <c>ConnectionStrings:Postgres</c> and the <c>Email</c> section directly
        /// as environment variables instead.
        /// </item>
        /// </list>
        /// </remarks>
        public static string? AddDotEnvFile(
            this IConfigurationBuilder builder,
            string fileName = DefaultFileName,
            string contentRootPath = "")
        {
            var path = FindFileUpwards(fileName, contentRootPath);
            if (path is null)
            {
                return null;
            }

            var values = Parse(File.ReadAllLines(path));
            AddDerivedPostgresConnectionString(values);
            AddDerivedRedisConnectionString(values);
            AddDerivedCorsSettings(values);
            AddApplicationSettings(values);

            // Inserted at the front on purpose: the last provider that knows a key wins, so the
            // .env file has to come first to stay the lowest priority one. Everything configured in
            // appsettings.json, in user-secrets or in environment variables overrides it.
            builder.Sources.Insert(0, new MemoryConfigurationSource { InitialData = values });

            return path;
        }

        /// <summary>
        /// Walks up from <paramref name="startDirectory"/> looking for <paramref name="fileName"/>
        /// and returns the full path of the first match.
        /// </summary>
        private static string? FindFileUpwards(string fileName, string startDirectory)
        {
            var directory = string.IsNullOrWhiteSpace(startDirectory)
                ? Directory.GetCurrentDirectory()
                : Path.GetFullPath(startDirectory);

            for (var depth = 0; depth <= MaxParentDirectoryDepth; depth++)
            {
                var candidate = Path.Combine(directory, fileName);
                if (File.Exists(candidate))
                {
                    return candidate;
                }

                var parent = Directory.GetParent(directory);
                if (parent is null)
                {
                    break;
                }

                directory = parent.FullName;
            }

            return null;
        }

        /// <summary>
        /// Parses <c>KEY=VALUE</c> lines into a configuration dictionary. Empty lines and comments
        /// are skipped, the key is everything before the first <c>=</c>, and surrounding quotes of
        /// the value are removed so that quoted values are usable as-is.
        /// </summary>
        private static Dictionary<string, string?> Parse(IEnumerable<string> lines)
        {
            var values = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);

            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed.Length == 0 || trimmed.StartsWith('#'))
                {
                    continue;
                }

                var separator = trimmed.IndexOf('=');
                if (separator < 1)
                {
                    continue;
                }

                var key = trimmed[..separator].Trim();
                var value = trimmed[(separator + 1)..].Trim();

                if (key.Length == 0)
                {
                    continue;
                }

                if (value.Length >= 2
                    && ((value[0] == '"' && value[^1] == '"') || (value[0] == '\'' && value[^1] == '\'')))
                {
                    value = value[1..^1];
                }

                values[key] = value;
            }

            return values;
        }

        /// <summary>
        /// Composes <c>ConnectionStrings:Postgres</c> from the <c>POSTGRES_*</c> secrets of the
        /// <c>.env</c> file, so the credentials generated by <c>scripts\init-secrets.ps1</c> are used
        /// as they are, without keeping a second copy of the password.
        /// This is the only place in this file that knows about compose specific key names.
        /// </summary>
        /// <remarks>
        /// A partial set of secrets is ignored, so the data access layer fails with one descriptive
        /// error instead of connecting with an empty password.
        /// </remarks>
        private static void AddDerivedPostgresConnectionString(Dictionary<string, string?> values)
        {
            if (!values.TryGetValue(DatabaseKey, out var database) || string.IsNullOrWhiteSpace(database)
                || !values.TryGetValue(UsernameKey, out var username) || string.IsNullOrWhiteSpace(username)
                || !values.TryGetValue(PasswordKey, out var password) || string.IsNullOrWhiteSpace(password))
            {
                return;
            }

            var host = values.TryGetValue(HostKey, out var configuredHost) && !string.IsNullOrWhiteSpace(configuredHost)
                ? configuredHost
                : DefaultHost;
            var port = values.TryGetValue(PortKey, out var configuredPort) && !string.IsNullOrWhiteSpace(configuredPort)
                ? configuredPort
                : DefaultPort;

            values[$"ConnectionStrings:{ServiceCollectionExtensions.PostgresConnectionName}"] = string.Join(';',
                $"Host={host}",
                $"Port={port}",
                $"Database={database}",
                $"Username={username}",
                $"Password={password}");
        }

        /// <summary>
        /// Composes <c>ConnectionStrings:Redis</c> from the <c>REDIS_*</c> secrets of the
        /// <c>.env</c> file, in the format StackExchange.Redis parses: comma separated options
        /// rather than the semicolon separated pairs Npgsql uses.
        /// </summary>
        /// <remarks>
        /// The user name is not optional. The compose redis runs with <c>user default off</c>,
        /// so an unauthenticated connection is impossible and a string without
        /// <c>user=</c> would be rejected. <c>abortConnect=false</c> is requested because
        /// <c>AddRedis</c> forces it anyway, and having it visible in the file makes the
        /// start-up tolerance of a missing redis obvious to whoever reads it.
        /// </remarks>
        private static void AddDerivedRedisConnectionString(Dictionary<string, string?> values)
        {
            if (!values.TryGetValue(RedisUsernameKey, out var username) || string.IsNullOrWhiteSpace(username)
                || !values.TryGetValue(RedisPasswordKey, out var password) || string.IsNullOrWhiteSpace(password))
            {
                return;
            }

            var host = values.TryGetValue(RedisHostKey, out var configuredHost) && !string.IsNullOrWhiteSpace(configuredHost)
                ? configuredHost
                : DefaultHost;
            var port = values.TryGetValue(RedisPortKey, out var configuredPort) && !string.IsNullOrWhiteSpace(configuredPort)
                ? configuredPort
                : DefaultRedisPort;

            values[$"ConnectionStrings:{ServiceCollectionExtensions.RedisConnectionName}"] = string.Join(',',
                $"{host}:{port}",
                $"user={username}",
                $"password={password}",
                "abortConnect=false");
        }

        /// <summary>
        /// Copies the application secrets of the <c>.env</c> file straight into configuration keys,
        /// so a tracked <c>appsettings.json</c> never has to hold a credential.
        /// </summary>
        /// <remarks>
        /// An empty <c>.env</c> value adds nothing at all rather than adding an empty setting. That
        /// matters because the file is inserted as the lowest priority source: an empty value it
        /// supplied would sit <em>below</em> appsettings.json and user-secrets anyway, so writing it
        /// would only suggest that the setting was configured when it is not. Leaving the key absent
        /// also means the options class default applies, which is where a default belongs.
        ///
        /// The values are not quoted or escaped on the way in - the parser already removed any
        /// surrounding quotes, so a secret containing <c>=</c> or <c>;</c> is usable as long as it is
        /// written quoted. This is the same rule the connection strings above follow, and the reason
        /// <c>scripts\init-secrets.ps1</c> can generate hex.
        /// </remarks>
        private static void AddApplicationSettings(Dictionary<string, string?> values)
        {
            foreach (var (envKey, configurationKey) in ApplicationSecretKeys)
            {
                if (values.TryGetValue(envKey, out var value) && !string.IsNullOrWhiteSpace(value))
                {
                    values[configurationKey] = value;
                }
            }
        }

        /// <summary>
        /// Turns <c>CORS_ENABLED</c> and <c>CORS_ALLOWED_ORIGINS</c> into the configuration keys the
        /// browser policy reads.
        /// </summary>
        /// <remarks>
        /// The origins become indexed children, which is how the configuration system represents a
        /// list from a flat source. Writing them this way is also why the array must not exist in
        /// <c>appsettings.json</c>: a list coming from two providers does not merge, the higher
        /// priority one simply wins per index, so a committed default would shadow this file and
        /// quietly replace the developer's own origin with the author's.
        ///
        /// An empty value leaves the key absent, which is not the same as an empty list: absent
        /// means the switch keeps its default of on, and an empty list means no browser is allowed.
        /// A blank line in the template therefore does not disable the policy.
        /// </remarks>
        private static void AddDerivedCorsSettings(Dictionary<string, string?> values)
        {
            if (values.TryGetValue(CorsEnabledKey, out var enabled) && !string.IsNullOrWhiteSpace(enabled))
            {
                values[CorsExtensions.EnabledKey] = enabled;
            }

            if (!values.TryGetValue(CorsOriginsKey, out var origins) || string.IsNullOrWhiteSpace(origins))
            {
                return;
            }

            var index = 0;
            foreach (var origin in origins.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                values[$"{CorsExtensions.OriginsSectionName}:{index}"] = origin;
                index++;
            }
        }
    }
}
